[core]
computerName=yuwk_home
lastVersion=1.26.0.0
coreMode=2
port=24802
interface=192.168.31.101
preventSleep=false
language=zh_CN
wlClipboard=false
processMode=0

[internalConfig]
numColumns=5
numRows=3
hasHeartbeat=false
heartbeat=5000
protocol=1
relativeMouseMoves=false
win32KeepForeground=false
hasSwitchDelay=false
switchDelay=250
hasSwitchDoubleTap=false
switchDoubleTap=250
switchCornerSize=0
defaultLockToScreenState=false
disableLockToScreen=false
clipboardSharing=true
clipboardSharingSize=10240
switchCornerArray\1\switchCorner=false
switchCornerArray\2\switchCorner=false
switchCornerArray\3\switchCorner=false
switchCornerArray\4\switchCorner=false
switchCornerArray\size=4
screens\1\name=
screens\2\name=
screens\3\name=
screens\4\name=
screens\5\name=
screens\6\name=
screens\7\name=Mac
screens\8\name=yuwk_home
screens\9\name=192.168.31.48
screens\10\name=
screens\11\name=
screens\12\name=
screens\13\name=
screens\14\name=
screens\15\name=
screens\size=15
hotkeys\size=0
screens\8\switchCornerSize=0
screens\8\aliasArray\size=0
screens\8\modifierArray\1\modifier=0
screens\8\modifierArray\2\modifier=1
screens\8\modifierArray\3\modifier=2
screens\8\modifierArray\4\modifier=3
screens\8\modifierArray\5\modifier=4
screens\8\modifierArray\6\modifier=5
screens\8\modifierArray\size=6
screens\8\switchCornerArray\1\switchCorner=false
screens\8\switchCornerArray\2\switchCorner=false
screens\8\switchCornerArray\3\switchCorner=false
screens\8\switchCornerArray\4\switchCorner=false
screens\8\switchCornerArray\size=4
screens\8\fixArray\1\fix=false
screens\8\fixArray\2\fix=false
screens\8\fixArray\3\fix=false
screens\8\fixArray\4\fix=false
screens\8\fixArray\size=4
screens\7\switchCornerSize=0
screens\7\aliasArray\size=0
screens\7\modifierArray\1\modifier=0
screens\7\modifierArray\2\modifier=3
screens\7\modifierArray\3\modifier=2
screens\7\modifierArray\4\modifier=1
screens\7\modifierArray\5\modifier=1
screens\7\modifierArray\6\modifier=5
screens\7\modifierArray\size=6
screens\7\switchCornerArray\1\switchCorner=false
screens\7\switchCornerArray\2\switchCorner=false
screens\7\switchCornerArray\3\switchCorner=false
screens\7\switchCornerArray\4\switchCorner=false
screens\7\switchCornerArray\size=4
screens\7\fixArray\1\fix=false
screens\7\fixArray\2\fix=false
screens\7\fixArray\3\fix=false
screens\7\fixArray\4\fix=false
screens\7\fixArray\size=4
screens\9\switchCornerSize=0
screens\9\aliasArray\size=0
screens\9\modifierArray\1\modifier=0
screens\9\modifierArray\2\modifier=1
screens\9\modifierArray\3\modifier=2
screens\9\modifierArray\4\modifier=3
screens\9\modifierArray\5\modifier=4
screens\9\modifierArray\6\modifier=5
screens\9\modifierArray\size=6
screens\9\switchCornerArray\1\switchCorner=false
screens\9\switchCornerArray\2\switchCorner=false
screens\9\switchCornerArray\3\switchCorner=false
screens\9\switchCornerArray\4\switchCorner=false
screens\9\switchCornerArray\size=4
screens\9\fixArray\1\fix=false
screens\9\fixArray\2\fix=false
screens\9\fixArray\3\fix=false
screens\9\fixArray\4\fix=false
screens\9\fixArray\size=4

[gui]
logExpanded=true
enableUpdateCheck=false
startCoreWithGui=true
shownFirstConnectedMessage=true
closeReminder=false
shownServerFirstStartMessage=true
autoHide=true
closeToTray=true
symbolicTrayIcon=true
showVersionInTitle=false

[client]
remoteHost=192.168.31.85

[server]
externalConfig=false
externalConfigFile=C:/ProgramData/Deskflow/deskflow-server.conf

[log]
level=4
toFile=false
file=C:/Users/17290/deskflow.log
guiDebug=false

[daemon]
elevate=true

[security]
certificate=C:/ProgramData/Deskflow/tls/deskflow.pem
keySize=2048
tlsEnabled=true
checkPeerFingerprints=true
